const TYPES={fire:{name:'火',color:'#ff795c',state:'burning',icon:'🔥'},water:{name:'水',color:'#53a8ff',state:'wet',icon:'💧'},frost:{name:'冰',color:'#8ee6ff',state:'frozen',icon:'❄️'},toxin:{name:'毒',color:'#b887ff',state:'poisoned',icon:'☠️'}};
const STATES={burning:{name:'燃烧',icon:'🔥'},wet:{name:'潮湿',icon:'💧'},frozen:{name:'冻结',icon:'❄️'},poisoned:{name:'中毒',icon:'☠️'}};
const arena=document.querySelector('#arena'),attributeControls=document.querySelector('#attributeControls'),environmentControls=document.querySelector('#environmentControls'),statusButtons=document.querySelector('#statusButtons'),statusList=document.querySelector('#statusList'),eventLog=document.querySelector('#eventLog');
let entities=[],selectedId=null,running=false,tick=0,timer=null,nextId=1;
const env={enabled:true,attrs:{fire:0,water:0,frost:0,toxin:0}};
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n));
function makeEntity(name,x,y,attrs={}){const state=Object.fromEntries(Object.keys(STATES).map(k=>[k,{active:false,entry:0,exit:0}]));return{id:nextId++,name,x,y,attrs:{fire:0,water:0,frost:0,toxin:0,...attrs},state};}
function seed(){entities=[makeEntity('篝火',27,42,{fire:80}),makeEntity('水元素',66,47,{water:70}),makeEntity('测试体',47,72,{})];selectedId=entities[2].id;tick=0;env.attrs={fire:0,water:0,frost:0,toxin:0};renderAll();log('实验场已重置');}
function rangeControl(container,key,value,onInput){const node=document.querySelector('#rangeTemplate').content.firstElementChild.cloneNode(true);node.querySelector('.range-name').textContent=TYPES[key].name;node.querySelector('.range-name').style.color=TYPES[key].color;const input=node.querySelector('input'),out=node.querySelector('output');input.value=value;out.value=value;input.addEventListener('input',()=>{out.value=input.value;onInput(+input.value)});container.append(node);}
function buildControls(){attributeControls.innerHTML='';environmentControls.innerHTML='';Object.keys(TYPES).forEach(k=>{rangeControl(attributeControls,k,0,v=>{const e=getSelected();if(e){e.attrs[k]=v;renderEntities();}});rangeControl(environmentControls,k,env.attrs[k],v=>env.attrs[k]=v)});statusButtons.innerHTML='';Object.entries(STATES).forEach(([k,s])=>{const b=document.createElement('button');b.textContent=`${s.icon} ${s.name}`;b.onclick=()=>applyState(k);statusButtons.append(b)});}
function renderAll(){renderEntities();renderInspector();document.querySelector('#tickLabel').textContent=`TICK ${String(tick).padStart(4,'0')}`;}
function renderEntities(){arena.querySelectorAll('.entity').forEach(n=>n.remove());for(const e of entities){const el=document.createElement('div');el.className='entity'+(e.id===selectedId?' selected':'');el.dataset.id=e.id;el.style.left=e.x+'%';el.style.top=e.y+'%';const colors=Object.entries(e.attrs).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]).map(([k])=>TYPES[k].color);if(colors.length)el.style.background=`radial-gradient(circle at 45% 38%,#294155,#14222f 68%),conic-gradient(${colors.join(',')})`;el.style.boxShadow=`0 0 0 3px ${colors[0]||'#486071'},0 10px 25px #0008`;const active=Object.entries(e.state).filter(([,v])=>v.active).map(([k])=>STATES[k].icon).join('');el.innerHTML=`<div class="entity-core"><span class="entity-icon">◉</span><div class="entity-name"></div><div class="entity-states">${active}</div></div>`;el.querySelector('.entity-name').textContent=e.name;bindEntity(el,e);arena.append(el)}}
function bindEntity(el,e){el.addEventListener('pointerdown',ev=>{selectedId=e.id;renderInspector();arena.querySelectorAll('.entity').forEach(n=>n.classList.toggle('selected',+n.dataset.id===e.id));el.setPointerCapture(ev.pointerId);const move=m=>{const r=arena.getBoundingClientRect();e.x=clamp((m.clientX-r.left)/r.width*100,6,94);e.y=clamp((m.clientY-r.top)/r.height*100,8,92);el.style.left=e.x+'%';el.style.top=e.y+'%'};el.onpointermove=move;el.onpointerup=()=>{el.onpointermove=null;el.onpointerup=null}});}
function getSelected(){return entities.find(e=>e.id===selectedId)}
function renderInspector(){const e=getSelected(),empty=document.querySelector('#emptyInspector'),box=document.querySelector('#entityInspector'),del=document.querySelector('#deleteBtn');empty.classList.toggle('hidden',!!e);box.classList.toggle('hidden',!e);del.disabled=!e;document.querySelector('#selectedName').textContent=e?e.name:'未选择实体';if(!e)return;const name=document.querySelector('#nameInput');name.value=e.name;[...attributeControls.querySelectorAll('.range-row')].forEach((row,i)=>{const k=Object.keys(TYPES)[i],input=row.querySelector('input'),out=row.querySelector('output');input.value=e.attrs[k];out.value=e.attrs[k]});statusList.innerHTML='';Object.entries(e.state).forEach(([k,v])=>{const s=STATES[k],card=document.createElement('div');card.className='status-card'+(v.active?' active':'');card.innerHTML=`<div class="status-head"><span>${s.icon} ${s.name}</span><span>${v.active?'生效中':'未生效'}</span></div><div class="meter-label"><span>进入 ${Math.round(v.entry)}</span><span>退出 ${Math.round(v.exit)}</span></div><div class="meter"><i style="width:${v.active?v.exit:v.entry}%"></i></div>`;statusList.append(card)})}
function applyState(k){const e=getSelected();if(!e)return;const s=e.state[k];if(!s.active){s.entry=100;s.active=true;s.exit=0;log(`${e.name} 被直接施加「${STATES[k].name}」`)}else{s.exit=100;exitState(e,k)}renderAll()}
function log(text){const d=document.createElement('div');d.className='log-item';d.innerHTML=`<b>${String(tick).padStart(4,'0')}</b> · ${text}`;eventLog.prepend(d);while(eventLog.children.length>60)eventLog.lastChild.remove()}
function distance(a,b){const r=arena.getBoundingClientRect(),dx=(a.x-b.x)/100*r.width,dy=(a.y-b.y)/100*r.height;return Math.hypot(dx,dy)}
function effectiveAttrs(source){const a={...source.attrs};const fireWater=Math.min(a.fire,a.water)*.55;a.fire-=fireWater;a.water-=fireWater;const fireIce=Math.min(a.fire,a.frost)*.7;a.fire-=fireIce;a.frost-=fireIce;return a}
function enterState(e,k){const s=e.state[k];if(!s.active&&s.entry>=100){s.active=true;s.entry=100;s.exit=0;log(`${e.name} 进入「${STATES[k].name}」状态`)}}
function exitState(e,k){const s=e.state[k];if(s.active&&s.exit>=100){s.active=false;s.entry=0;s.exit=0;log(`${e.name} 退出「${STATES[k].name}」状态`)}}
function simulate(){tick++;const incoming=new Map(entities.map(e=>[e.id,{fire:0,water:0,frost:0,toxin:0}]));arena.querySelectorAll('.entity').forEach(n=>n.classList.remove('overlap'));for(let i=0;i<entities.length;i++)for(let j=i+1;j<entities.length;j++){const a=entities[i],b=entities[j];if(distance(a,b)<84){const aa=effectiveAttrs(a),bb=effectiveAttrs(b);Object.keys(TYPES).forEach(k=>{incoming.get(a.id)[k]+=bb[k];incoming.get(b.id)[k]+=aa[k]});arena.querySelector(`[data-id="${a.id}"]`)?.classList.add('overlap');arena.querySelector(`[data-id="${b.id}"]`)?.classList.add('overlap')}}for(const e of entities){const inc=incoming.get(e.id);if(env.enabled)Object.keys(TYPES).forEach(k=>inc[k]+=effectiveAttrs(env)[k]);Object.entries(TYPES).forEach(([k,t])=>{const s=e.state[t.state],power=inc[k];if(power>0){if(!s.active){s.entry=clamp(s.entry+power*.045);s.exit=0;enterState(e,t.state)}else s.exit=clamp(s.exit-power*.025)}else if(s.active){s.exit=clamp(s.exit+1.25);exitState(e,t.state)}else s.entry=clamp(s.entry-1)});}
if(tick%2===0)renderAll();else document.querySelector('#tickLabel').textContent=`TICK ${String(tick).padStart(4,'0')}`;}
document.querySelector('#toggleBtn').onclick=()=>{running=!running;document.querySelector('#toggleBtn').textContent=running?'Ⅱ 暂停模拟':'▶ 启动模拟';if(running){timer=setInterval(simulate,100);log('模拟开始')}else{clearInterval(timer);log('模拟暂停')}};
document.querySelector('#resetBtn').onclick=()=>{running=false;clearInterval(timer);document.querySelector('#toggleBtn').textContent='▶ 启动模拟';seed()};
document.querySelector('#createBtn').onclick=()=>{const e=makeEntity(`实体 ${nextId}`,35+Math.random()*30,28+Math.random()*32);entities.push(e);selectedId=e.id;renderAll();log(`生成 ${e.name}`)};
document.querySelector('#deleteBtn').onclick=()=>{const e=getSelected();if(!e)return;entities=entities.filter(x=>x.id!==e.id);log(`删除 ${e.name}`);selectedId=entities[0]?.id??null;renderAll()};
document.querySelector('#nameInput').oninput=e=>{const x=getSelected();if(x){x.name=e.target.value||'未命名实体';document.querySelector('#selectedName').textContent=x.name;renderEntities()}};
document.querySelector('#envEnabled').onchange=e=>{env.enabled=e.target.checked;log(`环境影响已${env.enabled?'开启':'关闭'}`)};
document.querySelector('#clearLogBtn').onclick=()=>eventLog.innerHTML='';
buildControls();seed();
