(function(root){
const ATTR={fire:{name:'Fire',icon:'🔥',color:'#ff795c',state:'burning'},water:{name:'Water',icon:'💧',color:'#53a8ff',state:'wet'},frost:{name:'Ice',icon:'❄️',color:'#8ee6ff',state:'frozen'},toxin:{name:'Poison',icon:'☠️',color:'#b887ff',state:'poisoned'}};
const STATES={burning:{name:'Burning',icon:'🔥',attribute:'fire',triggers:{onEnter:[{kind:'AddAttribute',attribute:'fire',amount:1,duration:10}],onTick:[{kind:'RemoveStateProgress',state:'frozen',amount:5}],onExit:[]}},wet:{name:'Wet',icon:'💧',attribute:'water',triggers:{onEnter:[],onTick:[],onExit:[]}},frozen:{name:'Frozen',icon:'❄️',attribute:'frost',triggers:{onEnter:[],onTick:[{kind:'RemoveStateProgress',state:'burning',amount:5}],onExit:[]}},poisoned:{name:'Poisoned',icon:'☠️',attribute:'toxin',triggers:{onEnter:[],onTick:[],onExit:[]}}};
const clamp=n=>Math.max(0,Math.min(100,n));
const blankAttrs=()=>Object.fromEntries(Object.keys(ATTR).map(k=>[k,0]));
const blankStates=()=>Object.fromEntries(Object.keys(STATES).map(k=>[k,{active:false,entry:0,exit:0,nextTickAt:0,lastBand:0}]));
function createEntity(id,name,x=50,y=50,base={}){return{id,name,x,y,isEnvironment:false,enabled:true,baseAttributes:{...blankAttrs(),...base},contributions:[],states:blankStates()}}
function createEnvironment(id,name){const e=createEntity(id,name,0,0);e.isEnvironment=true;return e}
function getAttributeTotal(e,k){return e.baseAttributes[k]+e.contributions.filter(c=>c.attribute===k&&c.amount>0).reduce((n,c)=>n+c.amount,0)}
function setBaseAttribute(e,k,n){e.baseAttributes[k]=Math.max(0,n)}
function addContribution(e,k,n,source,duration,now=0){const c={id:`${source}-${now}-${Math.random()}`,attribute:k,amount:n,source,remainingMs:duration==null?null:duration*1000};e.contributions.push(c);return c}
function removeBaseAttribute(e,k,n){const removed=Math.min(e.baseAttributes[k],n);e.baseAttributes[k]-=removed;return removed}
function expireContributions(e,dt){const expired=[];e.contributions.forEach(c=>{if(c.remainingMs!=null){c.remainingMs-=dt;if(c.remainingMs<=0)expired.push(c)}});e.contributions=e.contributions.filter(c=>!expired.includes(c));return expired}
function addStateProgress(e,k,n){const s=e.states[k];if(!s)return 0;if(s.active)s.exit=clamp(s.exit-n);else s.entry=clamp(s.entry+n);return s.active?s.exit:s.entry}
function removeStateProgress(e,k,n){const s=e.states[k];if(!s)return 0;if(s.active)s.exit=clamp(s.exit+n);else s.entry=clamp(s.entry-n);return s.active?s.exit:s.entry}
function applyEffect(e,fx,source,now=0){if(fx.kind==='AddAttribute'){addContribution(e,fx.attribute,fx.amount,source,fx.duration,now);return`gains ${ATTR[fx.attribute].name} +${fx.amount}${fx.duration?` (${fx.duration}s)`:' (Permanent)'}`}if(fx.kind==='RemoveAttribute')return`loses Base ${ATTR[fx.attribute].name} ${removeBaseAttribute(e,fx.attribute,fx.amount)}`;if(fx.kind==='AddStateProgress'){addStateProgress(e,fx.state,fx.amount);return`${STATES[fx.state].name} progress +${fx.amount}`}if(fx.kind==='RemoveStateProgress'){removeStateProgress(e,fx.state,fx.amount);return`${STATES[fx.state].name} progress −${fx.amount}`}return'unknown effect ignored'}
function advanceEntity(e,influence={},dt=100,now=0){const events=[];Object.entries(STATES).forEach(([k,d])=>{const s=e.states[k],power=influence[d.attribute]||0;if(power>0){if(!s.active){const before=s.entry,oldBand=Math.floor(before/20);s.entry=clamp(s.entry+power*dt/100);s.exit=0;const band=Math.floor(s.entry/20);events.push({type:'progress',state:k,phase:'Enter',delta:+(s.entry-before).toFixed(1),value:s.entry,crossedBand:band>oldBand});if(s.entry>=100){s.active=true;s.entry=100;s.exit=0;s.nextTickAt=now+1000;events.push({type:'enter',state:k})}}else s.exit=clamp(s.exit-power*dt/400)}else if(s.active){const before=s.exit,oldBand=Math.floor(before/20);s.exit=clamp(s.exit+dt/100);const band=Math.floor(s.exit/20);events.push({type:'progress',state:k,phase:'Exit',delta:+(s.exit-before).toFixed(1),value:s.exit,crossedBand:band>oldBand});if(s.exit>=100){s.active=false;s.entry=0;s.exit=0;s.nextTickAt=0;events.push({type:'exit',state:k})}}else s.entry=clamp(s.entry-dt/500);if(s.active&&now>=s.nextTickAt){s.nextTickAt=now+1000;events.push({type:'tick',state:k})}});return events}
const api={ATTRIBUTE_DEFS:ATTR,STATE_DEFS:STATES,createEntity,createEnvironment,getAttributeTotal,setBaseAttribute,addContribution,removeBaseAttribute,expireContributions,addStateProgress,removeStateProgress,applyEffect,advanceEntity};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.StateSystem=api;
})(typeof window!=='undefined'?window:globalThis);
